### ISSUE TITLE
exception from 'eclipse' task

### ISSUE THREAD

**Issue by cahartm** [robi42/boot-rest#1]
thanks for the great project!  while attempting to build for eclipse, get an exception: http://pastebin.com/jQEmXSNM

with some help, moved the source/target compatibility out of ext{}, then got BUILD SUCCESSFUL ... these two lines:

```
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
```

**Comment by robi42** [comment]
Thanks, fixed.
